<a href="https://colab.research.google.com/github/Vykhrystenko/ML_FIT_3-9_Vykhrystenko/blob/main/%D0%92%D0%B8%D1%85%D1%80%D0%B8%D1%81%D1%82%D0%B5%D0%BD%D0%BA%D0%BE_3_9_%D0%A2%D1%80%D0%B5%D0%BD%D1%83%D0%B2%D0%B0%D0%BB%D1%8C%D0%BD%D0%B8%D0%B9_%D0%BD%D0%BE%D1%83%D1%82%D0%B1%D1%83%D0%BA_%D0%92%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_%D1%82%D0%B0_%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Тренувальний ноутбук: вектори, матриці та функції

Мета роботи — закріпити навички роботи з **NumPy**: створення та перетворення векторів і матриць, виконання арифметичних і лінійно-алгебраїчних операцій, використання математичних функцій та написання власних функцій.

### Правила виконання
- Виконуйте завдання послідовно.
- Для обчислень використовуйте `numpy`.
- Результати виводьте за допомогою `print()` або просто залишайте змінну останнім рядком комірки.
- Не змінюйте початкові дані, якщо це прямо не зазначено в умові.


## Підготовка

In [1]:
import numpy as np

np.set_printoptions(precision=3, suppress=True)


## Завдання 1. Створення векторів

1. Створіть вектор `a`, що містить числа від 1 до 10.
2. Створіть вектор `b` з 10 рівновіддалених значень від 0 до 1.
3. Виведіть обидва вектори та їх розмір.

In [12]:
# Код студента
a=np.arange(1, 11)
b = np.linspace(0, 1, 10)
print('Вектор a: ',a,'\nРозмір вектора a: ',a.size)
print('Вектор b: ',b,'\nРозмір вектора b: ',b.size)

Вектор a:  [ 1  2  3  4  5  6  7  8  9 10] 
Розмір вектора a:  10
Вектор b:  [0.    0.111 0.222 0.333 0.444 0.556 0.667 0.778 0.889 1.   ] 
Розмір вектора b:  10


## Завдання 2. Арифметичні дії з векторами

Нехай задано:

`x = [2, 4, 6, 8, 10]`  
`y = [1, 3, 5, 7, 9]`

Обчисліть:
- суму `x + y`;
- різницю `x - y`;
- поелементний добуток;
- поелементне ділення;
- квадрат кожного елемента вектора `x`.

In [15]:
x = np.array([2, 4, 6, 8, 10])
y = np.array([1, 3, 5, 7, 9])

# Код студента
print('Сума x+y: ',x+y)
print('Різниця x-y:',x-y)
print('Добуток x*y:',x*y)
print('Ділення x/y:',x/y)
print('Квадрат кожного елемента вектора x:',x*x)



Сума x+y:  [ 3  7 11 15 19]
Різниця x-y: [1 1 1 1 1]
Добуток x*y: [ 2 12 30 56 90]
Ділення x/y: [2.    1.333 1.2   1.143 1.111]
Квадрат кожного елемента вектора x: [  4  16  36  64 100]


## Завдання 3. Скалярний добуток і норма вектора

Для векторів `u = [3, -1, 2]` та `v = [1, 4, -2]`:

1. Обчисліть скалярний добуток.
2. Знайдіть евклідову норму кожного вектора.
3. Обчисліть косинус кута між векторами за формулою

\[
\cos(\alpha)=\frac{u\cdot v}{\|u\|\|v\|}
\]


In [16]:
u = np.array([3, -1, 2])
v = np.array([1, 4, -2])

# Код студента

dot_product = np.dot(u, v)

norm_u = np.linalg.norm(u)
norm_v = np.linalg.norm(v)

cos_alpha = dot_product / (norm_u * norm_v)

print(f"dot_product: {dot_product}")
print(f"norm_u: {norm_u}")
print(f"norm_v: {norm_v}")
print(f"cos_alpha: {cos_alpha}")

dot_product: -5
norm_u: 3.7416573867739413
norm_v: 4.58257569495584
cos_alpha: -0.2916059217599022


## Завдання 4. Індексація та логічні умови

Створіть вектор із чисел від `-10` до `10`.

За допомогою індексації та логічних масок:
- виберіть усі додатні елементи;
- виберіть усі парні елементи;
- замініть усі від'ємні значення на `0`;
- знайдіть кількість елементів, більших за `5`.

In [24]:
arr = np.arange(-10, 11)

# Код студента
print("Додатні елементи: ",arr[arr>0])
print("Парні елементи: ", arr[arr % 2 == 0])
view=arr[arr<0]
arr[arr < 0] = 0
print("Масив після заміни від'ємних значень на 0: ", arr)
print("Кількість елементів > 5:", np.sum(arr>5),)



Додатні елементи:  [ 1  2  3  4  5  6  7  8  9 10]
Парні елементи:  [-10  -8  -6  -4  -2   0   2   4   6   8  10]
Масив після заміни від'ємних значень на 0:  [ 0  0  0  0  0  0  0  0  0  0  0  1  2  3  4  5  6  7  8  9 10]
Кількість елементів > 5: 5


## Завдання 5. Створення матриць

Створіть:

1. Матрицю `A` розміру `3 × 3`, що містить числа від 1 до 9.
2. Нульову матрицю `3 × 4`.
3. Одиничну матрицю `4 × 4`.
4. Матрицю `2 × 5`, заповнену числом `7`.

Виведіть усі матриці.

In [29]:
# Код студента
A=np.arange(1,10).reshape(3,3)
Z=np.zeros((3,4))
Y=np.eye(4)
S=np.full((2,5),7)
print("Матриця A (3x3):\n", A)
print("\nНульова матриця (3x4):\n", Z)
print("\nОдинична матриця (4x4):\n", Y)
print("\n Матриця 2x5 (із 7):\n", S)


Матриця A (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Нульова матриця (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Одинична матриця (4x4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 Матриця 2x5 (із 7):
 [[7 7 7 7 7]
 [7 7 7 7 7]]


## Завдання 6. Доступ до елементів матриці

Для матриці

\[
M =
\begin{bmatrix}
5 & 2 & 7 & 1\\
3 & 8 & 4 & 6\\
9 & 0 & 2 & 5
\end{bmatrix}
\]

виконайте:
- отримайте другий рядок;
- отримайте третій стовпець;
- отримайте підматрицю з перших двох рядків і останніх двох стовпців;
- знайдіть максимальний і мінімальний елементи.

In [31]:
M = np.array([
    [5, 2, 7, 1],
    [3, 8, 4, 6],
    [9, 0, 2, 5]
])

# Код студента
print("Другий рядок:", M[1])
print("Третій стовпець:", M[:,2])
print("Підматриця:\n", M[:2, -2:])
print('Максимальний елемент: ',M.max(), 'Мінімальний елемент: ',M.min())

Другий рядок: [3 8 4 6]
Третій стовпець: [7 4 2]
Підматриця:
 [[7 1]
 [4 6]]
Максимальний елемент:  9 Мінімальний елемент:  0


## Завдання 7. Операції з матрицями

Нехай задано дві матриці:

\[
A =
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix},
\quad
B =
\begin{bmatrix}
5 & 6\\
7 & 8
\end{bmatrix}
\]

Обчисліть:
- `A + B`;
- `A - B`;
- поелементний добуток;
- матричний добуток `A @ B`;
- транспоновану матрицю `A`.

In [32]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Код студента
print("Додавання (A+B):\n", A+B)
print("\nВіднімання (A-B):\n", A-B)
print("\nПоелементний добуток (A*B):\n", A*B)
print("\nМатричний добуток (A@B):\n", A@B)
print("\nТранспонована матриця A(A.T):\n", A.T)

Додавання (A+B):
 [[ 6  8]
 [10 12]]

Віднімання (A-B):
 [[-4 -4]
 [-4 -4]]

Поелементний добуток (A*B):
 [[ 5 12]
 [21 32]]

Матричний добуток (A@B):
 [[19 22]
 [43 50]]

Транспонована матриця A(A.T):
 [[1 3]
 [2 4]]


## Завдання 8. Визначник та обернена матриця

Для матриці

\[
A =
\begin{bmatrix}
4 & 7\\
2 & 6
\end{bmatrix}
\]

1. Знайдіть визначник.
2. Знайдіть обернену матрицю.
3. Перевірте результат множенням `A @ A_inv`.
4. Поясніть у коментарі, який результат має бути отриманий.

In [34]:
A = np.array([[4, 7],
              [2, 6]])

#Код студента


print("Визначник :", np.linalg.det(A))
print("\nОбернена матриця :\n", np.linalg.inv(A))
print("\nПеревірка (A @ A_inv):\n", A@np.linalg.inv(A))



Визначник : 10.000000000000002

Обернена матриця :
 [[ 0.6 -0.7]
 [-0.2  0.4]]

Перевірка (A @ A_inv):
 [[ 1. -0.]
 [ 0.  1.]]


## Завдання 9. Розв'язання системи лінійних рівнянь

Розв'яжіть систему:

\[
\begin{cases}
2x + y = 5 \\
x - y = 1
\end{cases}
\]

Подайте коефіцієнти у вигляді матриці `A`, праву частину — вектора `b`, а потім використайте `np.linalg.solve()`.

In [35]:
# Код студента
A = np.array([
    [2, 1],
    [1, -1]
])

b = np.array([5, 1])

x, y = np.linalg.solve(A, b)

print(f"Розв'язок системи: x = {x:.1f}, y = {y:.1f}")



Розв'язок системи: x = 2.0, y = 1.0


## Завдання 10. Агрегувальні функції

Для матриці

```python
data = np.array([
    [10, 20, 30],
    [15, 25, 35],
    [12, 22, 32],
    [18, 28, 38]
])
```

знайдіть:
- суму всіх елементів;
- середнє значення;
- середнє по кожному стовпцю;
- суму по кожному рядку;
- стандартне відхилення;
- індекс максимального елемента в кожному рядку.

In [36]:
data = np.array([
    [10, 20, 30],
    [15, 25, 35],
    [12, 22, 32],
    [18, 28, 38]
])

# Код студента

print("Сума всіх елементів:", data.sum())
print('Загальне середнє значення: ', data.mean())
print("Середнє по кожному стовпцю:", data.mean(axis=0))
print("Сума по кожному рядку:", data.sum(axis=1))
print("Стандартне відхилення: ", data.std())
print("Індекс max елемента в кожному рядку:", data.argmax(axis=1))



Сума всіх елементів: 285
Загальне середнє значення:  23.75
Середнє по кожному стовпцю: [13.75 23.75 33.75]
Сума по кожному рядку: [60 75 66 84]
Стандартне відхилення:  8.709429755538917
Індекс max елемента в кожному рядку: [2 2 2 2]


## Завдання 11. Математичні функції NumPy

Створіть вектор із 9 значень від `-2` до `2`.

Для кожного значення обчисліть:
- квадрат;
- модуль;
- експоненту `e^x`;
- синус;
- косинус.

Окремо створіть вектор із додатних значень і обчисліть для нього натуральний логарифм та квадратний корінь.

In [39]:
# Код студента
x = np.linspace(-2, 2, 9)

print("Вектор x:", x)
print("Квадрат:", np.square(x))
print("Модуль:", np.abs(x))
print("Експонента:", np.exp(x))
print("Синус:", np.sin(x))
print("Косинус:", np.cos(x))

x_pos = x[x > 0]


print("\n\nДодатний вектор:", x_pos)
print("Натуральний логарифм (ln):", np.log(x_pos))
print("Квадратний корінь:", np.sqrt(x_pos))


Вектор x: [-2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2. ]
Квадрат: [4.   2.25 1.   0.25 0.   0.25 1.   2.25 4.  ]
Модуль: [2.  1.5 1.  0.5 0.  0.5 1.  1.5 2. ]
Експонента: [0.135 0.223 0.368 0.607 1.    1.649 2.718 4.482 7.389]
Синус: [-0.909 -0.997 -0.841 -0.479  0.     0.479  0.841  0.997  0.909]
Косинус: [-0.416  0.071  0.54   0.878  1.     0.878  0.54   0.071 -0.416]


Додатний вектор: [0.5 1.  1.5 2. ]
Натуральний логарифм (ln): [-0.693  0.     0.405  0.693]
Квадратний корінь: [0.707 1.    1.225 1.414]


## Завдання 12. Власна функція

Напишіть функцію `vector_stats(x)`, яка приймає числовий вектор і повертає:

- мінімум;
- максимум;
- середнє;
- медіану;
- стандартне відхилення.

Перевірте функцію на векторі:

`[4, 7, 1, 9, 3, 8, 5]`.

In [40]:
def vector_stats(x):
    min_val = np.min(x)
    max_val = np.max(x)
    mean_val = np.mean(x)
    median_val = np.median(x)
    std_val = np.std(x)

    return {
        "мінімум": min_val,
        "максимум": max_val,
        "середнє": mean_val,
        "медіана": median_val,
        "стандартне відхилення": std_val
    }


test_vector = np.array([4, 7, 1, 9, 3, 8, 5])

stats = vector_stats(test_vector)

for stat_name, value in stats.items():
    print(f"{stat_name.capitalize()}: {value:.4f}")


Мінімум: 1.0000
Максимум: 9.0000
Середнє: 5.2857
Медіана: 5.0000
Стандартне відхилення: 2.6573


## Завдання 13. Функція з умовою

Створіть функцію

\[
f(x) =
\begin{cases}
x^2, & x < 0 \\
2x + 1, & x \geq 0
\end{cases}
\]

Застосуйте її до вектора значень від `-5` до `5`.

Спробуйте реалізувати функцію двома способами:
1. через звичайну функцію Python;
2. через `np.where()`.

In [41]:
x = np.arange(-5, 6)

# Варіант 1
def f_python(x_val):
    if x_val < 0:
        return x_val ** 2
    else:
        return 2 * x_val + 1
y_variant1 = np.array([f_python(val) for val in x])
# Варіант 2
def f_numpy(x_arr):
    return np.where(x_arr < 0, x_arr ** 2, 2 * x_arr + 1)

y_variant2 = f_numpy(x)
print("Вхідний вектор x:", x)
print("Варіант 1 (Python):", y_variant1)
print("Варіант 2 (np.where):", y_variant2)

Вхідний вектор x: [-5 -4 -3 -2 -1  0  1  2  3  4  5]
Варіант 1 (Python): [25 16  9  4  1  1  3  5  7  9 11]
Варіант 2 (np.where): [25 16  9  4  1  1  3  5  7  9 11]


## Завдання 14. Робота з двовимірною функцією

Нехай

\[
f(x, y) = x^2 + 2y
\]

Задайте:

`x = [1, 2, 3]`  
`y = [10, 20, 30]`

1. Обчисліть значення функції поелементно.
2. Створіть усі можливі комбінації `x` та `y` за допомогою `np.meshgrid()`.
3. Обчисліть `f(x, y)` для кожної комбінації.

In [42]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

# Код студента
f_elementwise = x**2 + 2*y
X, Y = np.meshgrid(x, y)
f_grid = X**2 + 2*Y

print("Поелементний результат f(x, y):", f_elementwise)
print("\nМатриця комбінацій X:\n", X)
print("Матриця комбінацій Y:\n", Y)
print("\nЗначення f(x, y) для всіх комбінацій:\n", f_grid)



Поелементний результат f(x, y): [21 44 69]

Матриця комбінацій X:
 [[1 2 3]
 [1 2 3]
 [1 2 3]]
Матриця комбінацій Y:
 [[10 10 10]
 [20 20 20]
 [30 30 30]]

Значення f(x, y) для всіх комбінацій:
 [[21 24 29]
 [41 44 49]
 [61 64 69]]


## Завдання 15. Підсумкове

Згенеруйте матрицю `5 × 5` із випадкових цілих чисел від `1` до `100`.

Виконайте такі дії:
1. Знайдіть середнє значення кожного рядка.
2. Знайдіть середнє значення кожного стовпця.
3. Замініть усі елементи, менші за загальне середнє матриці, на `0`.
4. Знайдіть рядок із найбільшою сумою.
5. Нормалізуйте початкову матрицю за формулою:

\[
x_{norm} = \frac{x - x_{min}}{x_{max} - x_{min}}
\]

6. Напишіть функцію, яка виконує таку нормалізацію для довільної числової матриці.

In [43]:
rng = np.random.default_rng(42)
matrix = rng.integers(1, 101, size=(5, 5))

print("Початкова матриця:")
print(matrix)

# Код студента
row_means = matrix.mean(axis=1)

col_means = matrix.mean(axis=0)

matrix_filtered = matrix.copy()
matrix_filtered[matrix_filtered < matrix.mean()] = 0

max_sum_row_idx = matrix.sum(axis=1).argmax()
max_sum_row = matrix[max_sum_row_idx]

def normalize_matrix(mat):
    return (mat - mat.min()) / (mat.max() - mat.min())

matrix_normalized = normalize_matrix(matrix)

print("\nСереднє по рядках:", row_means)
print("\nСереднє по стовпцях:", col_means)
print("\nМатриця після заміни елементів < mean на 0:\n", matrix_filtered)
print(f"\nРядок з найбільшою сумою (індекс {max_sum_row_idx}):", max_sum_row)
print("\nНормалізована матриця (від 0 до 1):\n", matrix_normalized.round(4))


Початкова матриця:
[[ 9 78 66 44 44]
 [86  9 70 21 10]
 [53 98 74 77 72]
 [79 52 13 84 46]
 [51 38 19 93 79]]

Середнє по рядках: [48.2 39.2 74.8 54.8 56. ]

Середнє по стовпцях: [55.6 55.  48.4 63.8 50.2]

Матриця після заміни елементів < mean на 0:
 [[ 0 78 66  0  0]
 [86  0 70  0  0]
 [ 0 98 74 77 72]
 [79  0  0 84  0]
 [ 0  0  0 93 79]]

Рядок з найбільшою сумою (індекс 2): [53 98 74 77 72]

Нормалізована матриця (від 0 до 1):
 [[0.    0.775 0.64  0.393 0.393]
 [0.865 0.    0.685 0.135 0.011]
 [0.494 1.    0.73  0.764 0.708]
 [0.786 0.483 0.045 0.843 0.416]
 [0.472 0.326 0.112 0.944 0.786]]


## Короткий висновок

У 2–3 реченнях напишіть:
- які операції з векторами та матрицями були опрацьовані;
- які функції NumPy виявилися найкориснішими;
- що було найскладнішим у виконанні роботи.


In [ ]:
# За бажанням можна залишити висновок тут як текстовий рядок або коментар
#Протягом виконання даної роботи було опрацьовано векторні та матричні операції: обчислення базових статистик, умовну фільтрацію елементів, векторні обчислення та нормалізацію даних.
#Найзручнішими та найкориснішими виявилися прості функції np.mean(), np.min(), np.max() для швидких розрахунків, а також np.arange() та np.linspace() для генерації даних.
#Найбільшу увагу довелося приділити розрахунку нормалізації даних за формулою та правильному застосуванню умов до елементів масиву.
