<a href="https://colab.research.google.com/github/Vykhrystenko/ML_FIT_3-9_Vykhrystenko/blob/main/%D0%9B%D0%A0_%E2%84%961_%D0%92%D0%B8%D1%85%D1%80%D0%B8%D1%81%D1%82%D0%B5%D0%BD%D0%BA%D0%BE_3_9_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота 1. NumPy

**Тема:** основи роботи з бібліотекою NumPy, масиви, вектори та матриці.

### Правила роботи
- Виконуйте завдання послідовно.
- Для обчислень використовуйте можливості **NumPy**.
- Не замінюйте операції NumPy звичайними Python-циклами, якщо це прямо не вказано в умові.
- Після виконання кожного завдання виводьте отриманий результат.


## 0. Підготовка середовища

### Завдання 0
Імпортуйте бібліотеку NumPy з псевдонімом `np`. Виведіть версію встановленої бібліотеки NumPy.

In [1]:
# Код студента
!pip install numpy
import numpy as np

## 1. Створення масивів NumPy

### Завдання 1
Створіть одновимірний NumPy-масив із чисел:
`[2, 4, 6, 8, 10]`.

Виведіть масив та його тип за допомогою `type()`.

In [2]:
# Код студента
a=np.array([2,4,6,8,10])
print(a)
type(a)

[ 2  4  6  8 10]


numpy.ndarray

### Завдання 2
Створіть:
1. масив із 10 нулів;
2. масив із 8 одиниць;
3. масив із 6 елементів, усі значення яких дорівнюють `7`.

Використайте відповідні функції NumPy.

In [3]:
# Код студента
import numpy as np

zeros_array = np.zeros(10)

ones_array = np.ones(8)

sevens_array = np.full(6, 7)

### Завдання 3
Створіть масив цілих чисел від `1` до `20` включно.

Після цього створіть окремий масив парних чисел від `2` до `20`.

In [4]:
# Код студента
arr1 = np.arange(1, 21)

arr2 = np.arange(2, 21, 2)
print(arr1)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20]


### Завдання 4
За допомогою `np.linspace()` створіть масив із **11 рівновіддалених чисел** від `0` до `1` включно.

In [5]:
# Код студента
arr = np.linspace(0, 1, 11)
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### Завдання 5
Створіть матрицю розміром `3 × 4`, заповнену числами від `1` до `12`.

Спочатку створіть одновимірний масив, а потім змініть його форму.

In [6]:
# Код студента
arr = np.arange(1, 13)

arr2 = arr.reshape(3, 4)

arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## 2. Основні характеристики масивів

### Завдання 6
Для матриці, створеної у попередньому завданні, визначте та виведіть:
- кількість вимірів;
- форму;
- загальну кількість елементів;
- тип даних елементів.

Використайте атрибути `ndim`, `shape`, `size`, `dtype`.

In [7]:
# Код студента
print("ndim:", np.ndim(arr2))
print("shape:", np.shape(arr2))
print("size:", np.size(arr2))
print("dtype:", arr2.dtype)

ndim: 2
shape: (3, 4)
size: 12
dtype: int64


### Завдання 7
Створіть масив:
`[1.2, 3.5, 5.7, 7.9]`.

Перетворіть його елементи на цілі числа за допомогою `astype()` та виведіть новий масив.

In [8]:
# Код студента
arr=np.array([1.2, 3.5, 5.7, 7.9])
int_array=arr.astype(int)
print(arr)
print(int_array)

[1.2 3.5 5.7 7.9]
[1 3 5 7]


## 3. Індексація та зрізи

### Завдання 8
Створіть масив:
`[10, 20, 30, 40, 50, 60, 70, 80]`.

Виведіть:
1. перший елемент;
2. останній елемент;
3. елементи з індексами від `2` до `5` включно;
4. кожен другий елемент.

In [9]:
# Код студента
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print("Перший елемент:", arr[0])
print("Останній елемент:", arr[-1])
print("Елементи з індексами 2-5:", arr[2:6])
print("Кожен другий елемент:", arr[::2])

Перший елемент: 10
Останній елемент: 80
Елементи з індексами 2-5: [30 40 50 60]
Кожен другий елемент: [10 30 50 70]


### Завдання 9
Створіть матрицю:

```text
[[ 1,  2,  3,  4],
 [ 5,  6,  7,  8],
 [ 9, 10, 11, 12]]
```

Виведіть:
1. елемент `7`;
2. другий рядок;
3. третій стовпець;
4. підматрицю з останніх двох рядків і перших двох стовпців.

In [10]:
# Код студента
a=np.array([[ 1,  2,  3,  4],
 [ 5,  6,  7,  8],
 [ 9, 10, 11, 12]])
print("Елемент 7: ", a[1,2])
print("Другий рядок: ", a[1])
print("Третій стовпець:", a[:, 2])
print("Підматриця:\n", a[1:, :2])
print(a)

Елемент 7:  7
Другий рядок:  [5 6 7 8]
Третій стовпець: [ 3  7 11]
Підматриця:
 [[ 5  6]
 [ 9 10]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Завдання 10
Створіть масив чисел від `1` до `15`.

Замініть усі елементи з індексами від `5` до `9` включно на число `0`.

In [11]:
# Код студента
arr = np.arange(1, 16)
arr[5:10] = 0

print(arr)

[ 1  2  3  4  5  0  0  0  0  0 11 12 13 14 15]


## 4. Арифметичні операції та агрегатні функції

### Завдання 11
Створіть два масиви:

```python
a = [1, 2, 3, 4, 5]
b = [10, 20, 30, 40, 50]
```

Виконайте поелементно:
- додавання;
- віднімання;
- множення;
- ділення.

In [12]:
# Код студента
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
print('додавання', a+b)
print('віднімання', a-b)
print('множення', a*b)
print('ділення', a/b)

додавання [11 22 33 44 55]
віднімання [ -9 -18 -27 -36 -45]
множення [ 10  40  90 160 250]
ділення [0.1 0.1 0.1 0.1 0.1]


### Завдання 12
Для масиву:

`[4, 8, 15, 16, 23, 42]`

обчисліть:
- суму;
- середнє значення;
- мінімум;
- максимум;
- медіану;
- стандартне відхилення.

In [13]:
# Код студента
a=np.array([4, 8, 15, 16, 23, 42])
print("Сума:", np.sum(a))
print("Середнє значення:", np.mean(a))
print("Мінімум:", np.min(a))
print("Максимум:", np.max(a))
print("Медіана:", np.median(a))
print("Стандартне відхилення:", np.std(a))

Сума: 108
Середнє значення: 18.0
Мінімум: 4
Максимум: 42
Медіана: 15.5
Стандартне відхилення: 12.315302134607444


### Завдання 13
Створіть матрицю:

```text
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

Обчисліть:
1. суму всіх елементів;
2. суму по кожному стовпцю;
3. суму по кожному рядку;
4. середнє значення по кожному стовпцю.

In [14]:
# Код студента
arr=np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
print("Сума всіх елементів:", np.sum(arr))
print("Сума по стовпцях:", np.sum(arr, axis=0))
print("Сума по рядках:", np.sum(arr, axis=1))
print("Середнє по стовпцях:", np.mean(arr, axis=0))

Сума всіх елементів: 45
Сума по стовпцях: [12 15 18]
Сума по рядках: [ 6 15 24]
Середнє по стовпцях: [4. 5. 6.]


### Завдання 14
Для масиву чисел від `1` до `10` обчисліть:
- квадрат кожного елемента;
- квадратний корінь кожного елемента;
- натуральний логарифм кожного елемента.

Використайте функції NumPy.

In [15]:
# Код студента
arr = np.arange(1, 11)
squared = np.square(arr)
sqrt_vals = np.sqrt(arr)
log_vals = np.log(arr)

print("Квадрати:\n", squared)
print("\nКвадратні корені:\n", sqrt_vals)
print("\nНатуральні логарифми:\n", log_vals)

Квадрати:
 [  1   4   9  16  25  36  49  64  81 100]

Квадратні корені:
 [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]

Натуральні логарифми:
 [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


## 5. Логічні операції та фільтрація

### Завдання 15
Створіть масив:

`[3, 7, 12, 18, 21, 25, 30, 34]`

За допомогою булевої маски виведіть:
1. усі числа, більші за `15`;
2. усі парні числа;
3. числа в діапазоні від `10` до `30` включно.

In [16]:
# Код студента
arr = np.array([3, 7, 12, 18, 21, 25, 30, 34])

print("Більші за 15:", arr[arr > 15])
print("Парні числа:", arr[arr % 2 == 0])
print("У діапазоні 10-30:", arr[(arr >= 10) & (arr <= 30)])

Більші за 15: [18 21 25 30 34]
Парні числа: [12 18 30 34]
У діапазоні 10-30: [12 18 21 25 30]


### Завдання 16
Для масиву:

`[-5, 3, -2, 8, -1, 10, 0]`

замініть усі від’ємні значення на `0`.

Не використовуйте цикл `for`.

In [17]:
# Код студента
arr = np.array([-5, 3, -2, 8, -1, 10, 0])
arr[arr < 0] = 0

print(arr)

[ 0  3  0  8  0 10  0]


### Завдання 17
Створіть масив випадкових цілих чисел від `0` до `100` розміром `20`.

Порахуйте:
- скільки елементів більші за `50`;
- скільки елементів менші або дорівнюють `50`.

Для відтворюваності встановіть `np.random.seed(42)`.

In [18]:
# Код студента
np.random.seed(42)
arr = np.random.randint(0, 101, size=20)

print("Згенерований масив:\n", arr)
print("\nКількість елементів > 50:", np.sum(arr > 50))
print("Кількість елементів <= 50:", np.sum(arr <= 50))

Згенерований масив:
 [51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37]

Кількість елементів > 50: 12
Кількість елементів <= 50: 8


## 6. Зміна форми та об'єднання масивів

### Завдання 18
Створіть масив чисел від `1` до `24`.

Перетворіть його:
1. у матрицю `4 × 6`;
2. у матрицю `6 × 4`;
3. у тривимірний масив форми `2 × 3 × 4`.

Після кожного перетворення виведіть `shape`.

In [19]:
# Код студента
arr = np.arange(1, 25)

matrix_4x6 = arr.reshape(4, 6)
print("Матриця 4x6:")
print(matrix_4x6)
print("Форма (shape):", matrix_4x6.shape)

matrix_6x4 = arr.reshape(6, 4)
print("\nМатриця 6x4:")
print(matrix_6x4)
print("Форма (shape):", matrix_6x4.shape)

array_2x3x4 = arr.reshape(2, 3, 4)
print("\nТривимірний масив 2x3x4:")
print(array_2x3x4)
print("Форма (shape):", array_2x3x4.shape)

Матриця 4x6:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Форма (shape): (4, 6)

Матриця 6x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
Форма (shape): (6, 4)

Тривимірний масив 2x3x4:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Форма (shape): (2, 3, 4)


### Завдання 19
Створіть дві матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]
```

Об’єднайте їх:
1. вертикально;
2. горизонтально.

Використайте функції NumPy.

In [20]:
# Код студента
a=np.array([[1, 2],
     [3, 4]])
b=np.array([[5, 6],
     [7, 8]])
v_stacked = np.vstack((a, b))
h_stacked = np.hstack((a, b))

print("Вертикальне об'єднання:\n", v_stacked)
print("\nГоризонтальне об'єднання:\n", h_stacked)

Вертикальне об'єднання:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Горизонтальне об'єднання:
 [[1 2 5 6]
 [3 4 7 8]]


### Завдання 20
Створіть матрицю `3 × 4` із числами від `1` до `12`.

Перетворіть її назад в одновимірний масив двома способами:
- за допомогою `flatten()`;
- за допомогою `ravel()`.

Порівняйте результати.

In [21]:
# Код студента
matrix = np.arange(1, 13).reshape(3, 4)
arr_flatten = matrix.flatten()
arr_ravel = matrix.ravel()
print("\nМасив після flatten():", arr_flatten)
print("Масив після ravel():", arr_ravel)
print('Результати однакові: ', np.array_equal(arr_flatten,arr_ravel))


Масив після flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
Масив після ravel(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
Результати однакові:  True


## 7. Дії з векторами

### Завдання 21
Дано два вектори:

```text
a = [2, 4, 6]
b = [1, 3, 5]
```

Знайдіть:
- суму векторів;
- різницю векторів;
- результат множення кожного вектора на число `3`.

In [22]:
# Код студента
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

print("Сума (a + b):", a + b)
print("Різниця (a - b):", a - b)
print("Вектор a * 3:", a * 3)
print("Вектор b * 3:", b * 3)

Сума (a + b): [ 3  7 11]
Різниця (a - b): [1 1 1]
Вектор a * 3: [ 6 12 18]
Вектор b * 3: [ 3  9 15]


### Завдання 22
Для векторів:

```text
a = [1, 2, 3]
b = [4, 5, 6]
```

Обчисліть їх **скалярний добуток** двома способами:
1. за допомогою `np.dot()`;
2. за допомогою оператора `@`.

In [23]:
# Код студента
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot1 = np.dot(a, b)
dot2 = a @ b

print("Скалярний добуток (np.dot):", dot1)
print("Скалярний добуток (оператор @):", dot2)

Скалярний добуток (np.dot): 32
Скалярний добуток (оператор @): 32


### Завдання 23
Для вектора:

```text
v = [3, 4]
```

обчисліть його евклідову норму.

Потім нормалізуйте вектор, тобто отримайте вектор одиничної довжини.

In [24]:
# Код студента
v = np.array([3, 4])

norm = np.linalg.norm(v)
v_normalized = v / norm

print("Евклідова норма (довжина):", norm)
print("Нормалізований вектор:", v_normalized)

Евклідова норма (довжина): 5.0
Нормалізований вектор: [0.6 0.8]


### Завдання 24
Дано вектори:

```text
a = [1, 0, 0]
b = [0, 1, 0]
```

Знайдіть їх векторний добуток за допомогою `np.cross()`.

In [25]:
# Код студента
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])
cross_prod = np.cross(a, b)

print("Векторний добуток (a × b):", cross_prod)

Векторний добуток (a × b): [0 0 1]


### Завдання 25
Дано два вектори:

```text
a = [1, 2]
b = [2, 1]
```

Обчисліть косинус кута між ними за формулою через скалярний добуток і норми векторів.

Додатково знайдіть сам кут у градусах.

In [26]:
# Код студента
a = np.array([1, 2])
b = np.array([2, 1])

cos_theta = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
angle_deg = np.degrees(np.arccos(cos_theta))

print("Косинус кута (cos θ):", cos_theta)
print("Кут у градусах:", angle_deg)

Косинус кута (cos θ): 0.7999999999999998
Кут у градусах: 36.86989764584404


## 8. Дії з матрицями

### Завдання 26
Дано матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6]]
```

Знайдіть транспоновану матрицю двома способами:
1. за допомогою `.T`;
2. за допомогою `np.transpose()`.

In [27]:
# Код студента
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print("Оригінальна матриця A:")
print(A)

print("\nТранспонована через .T:")
print(A.T)

print("\nТранспонована через np.transpose():")
print(np.transpose(A))

Оригінальна матриця A:
[[1 2 3]
 [4 5 6]]

Транспонована через .T:
[[1 4]
 [2 5]
 [3 6]]

Транспонована через np.transpose():
[[1 4]
 [2 5]
 [3 6]]


### Завдання 27
Дано матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[2, 0],
     [1, 2]]
```

Обчисліть:
1. поелементний добуток `A * B`;
2. матричний добуток `A @ B`.

Поясніть у коментарі до коду, чим відрізняються ці операції.

In [28]:
# Код студента
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[2, 0],
              [1, 2]])
#Поелементне множення. Множення елементів з однаковим індексом
elementwise_prod = A * B
#Матричний добуток.Скалярний добуток рядків першої матриці на стовбці другої
matrix_prod = A @ B

print("Поелементний добуток (A * B):\n", elementwise_prod)
print("\nМатричний добуток (A @ B):\n", matrix_prod)

Поелементний добуток (A * B):
 [[2 0]
 [3 8]]

Матричний добуток (A @ B):
 [[ 4  4]
 [10  8]]


### Завдання 28
Для матриці:

```text
A = [[4, 7],
     [2, 6]]
```

обчисліть:
- визначник;
- обернену матрицю.

Перевірте результат, помноживши початкову матрицю на обернену.

In [29]:
# Код студента
A = np.array([[4, 7],
              [2, 6]])

det_A = np.linalg.det(A)

A_inv = np.linalg.inv(A)

identity_check = A @ A_inv

print("Визначник (det):", det_A)
print("\nОбернена матриця (A_inv):\n", A_inv)
print("\nПеревірка (A @ A_inv):\n", np.round(identity_check))

Визначник (det): 10.000000000000002

Обернена матриця (A_inv):
 [[ 0.6 -0.7]
 [-0.2  0.4]]

Перевірка (A @ A_inv):
 [[ 1. -0.]
 [ 0.  1.]]


### Завдання 29
Розв’яжіть систему лінійних рівнянь за допомогою NumPy:

```text
2x +  y = 5
 x + 3y = 6
```

Сформуйте матрицю коефіцієнтів `A` і вектор правих частин `b`.

Використайте `np.linalg.solve()`.

In [30]:
# Код студента
a = np.array([[2, 1],
              [1, 3]])

b = np.array([5, 6])

solution = np.linalg.solve(a, b)

print("Розв'язок системи [x, y]:", solution)

Розв'язок системи [x, y]: [1.8 1.4]


### Завдання 30
Створіть одиничну матрицю розміром `4 × 4`.

Перевірте властивість одиничної матриці: помножте на неї довільну матрицю `4 × 4` та порівняйте результат з початковою матрицею.

In [31]:
# Код студента
I = np.eye(4)
np.random.seed(42)
A = np.random.randint(1, 10, size=(4, 4))
result = A @ I

print("Одинична матриця I:\n", I)
print("\nДовільна матриця A:\n", A)
print("\nРезультат (A @ I):\n", result)

print("\nЧи збігається результат із матрицею A:", np.array_equal(A, result))

Одинична матриця I:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Довільна матриця A:
 [[7 4 8 5]
 [7 3 7 8]
 [5 4 8 8]
 [3 6 5 2]]

Результат (A @ I):
 [[7. 4. 8. 5.]
 [7. 3. 7. 8.]
 [5. 4. 8. 8.]
 [3. 6. 5. 2.]]

Чи збігається результат із матрицею A: True


## 9. Broadcasting (операція трансляції)

### Завдання 31
Створіть матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

Додайте число `10` до кожного її елемента.

In [32]:
# Код студента
A=np.array([[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]])
A+=10


In [33]:
A

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

### Завдання 32
До матриці:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

додайте вектор:

```text
v = [10, 20, 30]
```

Проаналізуйте, як NumPy застосував broadcasting.

In [34]:
# Код студента
A=np.array([[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]])
v=np.array([10,20,30])
A+=v

In [35]:
A

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

NumPy автоматично доповнив форму вектора v до форми матриці A (розмір 3×3),  скопіювавши його значення (10, 20, 30) для кожного рядка.

### Завдання 33
Нормалізуйте **кожен стовпець** матриці:

```text
A = [[10, 20, 30],
     [20, 30, 40],
     [30, 40, 50]]
```

за формулою:

\[
z = \frac{x - \mu}{\sigma}
\]

де `μ` — середнє значення стовпця, `σ` — стандартне відхилення стовпця.

Не використовуйте цикл `for`.

In [36]:
# Код студента
A = np.array([[10, 20, 30],
              [20, 30, 40],
              [30, 40, 50]])

mu = np.mean(A, axis=0)
sigma = np.std(A, axis=0)
z = (A - mu) / sigma

print(z)

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


## 10. Випадкові дані

### Завдання 34
Встановіть `np.random.seed(42)` та створіть:
1. 10 випадкових цілих чисел від `1` до `100`;
2. матрицю `3 × 3` випадкових чисел від `0` до `1`;
3. 1000 значень із нормального розподілу.

Для третього масиву обчисліть середнє та стандартне відхилення.

In [37]:
# Код студента
np.random.seed(42)

random_ints = np.random.randint(1, 101, size=10)

random_matrix = np.random.rand(3, 3)

normal_values = np.random.randn(1000)
mean_val = np.mean(normal_values)
std_val = np.std(normal_values)

print("10 цілих чисел:", random_ints)
print("\nМатриця 3x3:\n", random_matrix)
print("\nНормальний розподіл - Середнє:", mean_val)
print("Нормальний розподіл - Стандартне відхилення:", std_val)

10 цілих чисел: [52 93 15 72 61 21 83 87 75 75]

Матриця 3x3:
 [[0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264]
 [0.21233911 0.18182497 0.18340451]]

Нормальний розподіл - Середнє: 0.02216865975826456
Нормальний розподіл - Стандартне відхилення: 0.9792284455184356


### Завдання 35
Змоделюйте оцінки 30 студентів — випадкові цілі числа від `0` до `100`.

Визначте:
- середню оцінку;
- медіану;
- найвищу та найнижчу оцінки;
- кількість студентів, які отримали не менше `60`;
- відсоток студентів, які отримали не менше `90`.

In [38]:
# Код студента
scores = np.random.randint(0, 101, size=30)

print("Оцінки студентів:", scores)
print("Середня оцінка:", np.mean(scores))
print("Медіана:", np.median(scores))
print("Найвища оцінка:", np.max(scores))
print("Найнижча оцінка:", np.min(scores))
print("Кількість студентів (>= 60):", np.sum(scores >= 60))
print("Відсоток студентів (>= 90):", f"{np.mean(scores >= 90) * 100}%")

Оцінки студентів: [25  2 40 59 13 74 81 11 86 11 12 24 44 18 54 99 44  7 92 52 54 31 50 43
 81 69 17 82 21 36]
Середня оцінка: 44.4
Медіана: 43.5
Найвища оцінка: 99
Найнижча оцінка: 2
Кількість студентів (>= 60): 8
Відсоток студентів (>= 90): 6.666666666666667%


## 11. Підсумкові завдання

### Завдання 36
Дано результати продажів трьох товарів за чотири місяці:

```text
sales = [[120, 150, 170, 160],
         [80,  90,  100, 110],
         [200, 180, 210, 230]]
```

Рядки — товари, стовпці — місяці.

Визначте:
1. загальний обсяг продажів кожного товару;
2. загальний обсяг продажів у кожному місяці;
3. товар із найбільшими сумарними продажами;
4. місяць із найбільшим загальним обсягом продажів;
5. середній обсяг продажів кожного товару.

In [39]:
# Код студента
sales = np.array([[120, 150, 170, 160],
                  [80, 90, 100, 110],
                  [200, 180, 210, 230]])

total_per_product = np.sum(sales, axis=1)

total_per_month = np.sum(sales, axis=0)

max_product = np.argmax(total_per_product) + 1

max_month = np.argmax(total_per_month) + 1

mean_per_product = np.mean(sales, axis=1)

print("1. Загальний обсяг продажів кожного товару:", total_per_product)
print("2. Загальний обсяг продажів у кожному місяці:", total_per_month)
print(f"3. Товар із найбільшими сумарними продажами: Товар {max_product}")
print(f"4. Місяць із найбільшим загальним обсягом продажів: Місяць {max_month}")
print("5. Середній обсяг продажів кожного товару:", mean_per_product)

1. Загальний обсяг продажів кожного товару: [600 380 820]
2. Загальний обсяг продажів у кожному місяці: [400 420 480 500]
3. Товар із найбільшими сумарними продажами: Товар 3
4. Місяць із найбільшим загальним обсягом продажів: Місяць 4
5. Середній обсяг продажів кожного товару: [150.  95. 205.]


### Завдання 37
Створіть квадратну матрицю `5 × 5` із випадкових цілих чисел від `1` до `20`.

Виконайте:
1. знайдіть суму головної діагоналі;
2. знайдіть суму побічної діагоналі;
3. знайдіть максимальний елемент кожного рядка;
4. знайдіть мінімальний елемент кожного стовпця;
5. замініть усі елементи, менші за середнє значення всієї матриці, на `0`.

In [40]:
# Код студента
np.random.seed(42)

matrix = np.random.randint(1, 21, size=(5, 5))
print("Початкова матриця:\n", matrix)

main_diag_sum = np.trace(matrix)

anti_diag_sum = np.trace(np.fliplr(matrix))

max_per_row = np.max(matrix, axis=1)

min_per_col = np.min(matrix, axis=0)

mean_val = np.mean(matrix)
modified_matrix = matrix.copy()
modified_matrix[modified_matrix < mean_val] = 0

print("\n1. Сума головної діагоналі:", main_diag_sum)
print("2. Сума побічної діагоналі:", anti_diag_sum)
print("3. Максимальний елемент кожного рядка:", max_per_row)
print("4. Мінімальний елемент кожного стовпця:", min_per_col)
print(f"5. Матриця після заміни (середнє було {mean_val:.2f}):\n", modified_matrix)

Початкова матриця:
 [[ 7 20 15 11  8]
 [ 7 19 11 11  4]
 [ 8  3  2 12  6]
 [ 2  1 12 12 17]
 [10 16 15 15 19]]

1. Сума головної діагоналі: 59
2. Сума побічної діагоналі: 32
3. Максимальний елемент кожного рядка: [20 19 12 17 19]
4. Мінімальний елемент кожного стовпця: [ 2  1  2 11  4]
5. Матриця після заміни (середнє було 10.52):
 [[ 0 20 15 11  0]
 [ 0 19 11 11  0]
 [ 0  0  0 12  0]
 [ 0  0 12 12 17]
 [ 0 16 15 15 19]]


### Завдання 38
Дано матрицю ознак трьох об’єктів:

```text
X = [[2, 4, 6],
     [1, 3, 5],
     [5, 7, 9]]
```

Обчисліть **евклідову відстань** між:
- першим і другим рядком;
- першим і третім рядком;
- другим і третім рядком.

Використайте операції NumPy та `np.linalg.norm()`.

In [41]:
# Код студента
x = np.array([[2, 4, 6],
              [1, 3, 5],
              [5, 7, 9]])

dist_12 = np.linalg.norm(x[0] - x[1])
dist_13 = np.linalg.norm(x[0] - x[2])
dist_23 = np.linalg.norm(x[1] - x[2])

print("Евклідова відстань між 1 і 2 рядком:", dist_12)
print("Евклідова відстань між 1 і 3 рядком:", dist_13)
print("Евклідова відстань між 2 і 3 рядком:", dist_23)

Евклідова відстань між 1 і 2 рядком: 1.7320508075688772
Евклідова відстань між 1 і 3 рядком: 5.196152422706632
Евклідова відстань між 2 і 3 рядком: 6.928203230275509


### Завдання 39
Створіть матрицю `4 × 4` із довільних цілих чисел.

Для кожного рядка знайдіть його норму та створіть нову матрицю, у якій кожен рядок нормалізований до одиничної довжини.

Спробуйте виконати завдання без циклів.

In [42]:
# Код студента
np.random.seed(42)
matrix = np.random.randint(1, 10, size=(4, 4))

norms = np.linalg.norm(matrix, axis=1, keepdims=True)

normalized_matrix = matrix / norms

print("Початкова матриця:\n", matrix)
print("\nНорми рядків:\n", norms)
print("\nНормалізована матриця:\n", normalized_matrix)

Початкова матриця:
 [[7 4 8 5]
 [7 3 7 8]
 [5 4 8 8]
 [3 6 5 2]]

Норми рядків:
 [[12.40967365]
 [13.07669683]
 [13.        ]
 [ 8.60232527]]

Нормалізована матриця:
 [[0.56407607 0.32232919 0.64465837 0.40291148]
 [0.53530338 0.22941573 0.53530338 0.61177529]
 [0.38461538 0.30769231 0.61538462 0.61538462]
 [0.34874292 0.69748583 0.58123819 0.23249528]]


### Завдання 40
Створіть матрицю коефіцієнтів і вектор правих частин для системи:

```text
 x + 2y +  z =  9
2x +  y -  z =  8
3x -  y + 2z =  3
```

1. Розв’яжіть систему за допомогою `np.linalg.solve()`.
2. Перевірте знайдений розв’язок матричним множенням `A @ x`.
3. Порівняйте результат із вектором `b`.

In [43]:
# Код студента
A = np.array([[1, 2, 1],
              [2, 1, -1],
              [3, -1, 2]])

b = np.array([9, 8, 3])

x = np.linalg.solve(A, b)
print("Розв'язок системи (x, y, z):", x)

check_b = A @ x
print("Результат множення A @ x:", check_b)

print("Збігається з вектором b:", np.allclose(check_b, b))

Розв'язок системи (x, y, z): [ 2.22222222  3.44444444 -0.11111111]
Результат множення A @ x: [9. 8. 3.]
Збігається з вектором b: True


---

## Самоперевірка

Після виконання роботи студент повинен уміти:
- створювати та перетворювати NumPy-масиви;
- використовувати індексацію та зрізи;
- виконувати векторизовані арифметичні операції;
- застосовувати агрегатні функції;
- використовувати булеві маски;
- змінювати форму та об'єднувати масиви;
- виконувати основні дії з векторами;
- виконувати основні операції з матрицями;
- застосовувати broadcasting;
- використовувати функції `numpy.linalg` для задач лінійної алгебри.


**Висновок**: протягом виконання даної лабораторної роботи було опановано ключові інструменти бібліотеки NumPy: створено й змінено структуру масивів, відпрацьовано індексацію, зрізи та роботу з булевими масками. Також засвоєно векторизовані обчислення, застосування агрегатних функцій, механізм broadcasting та вирішення задач лінійної алгебри за допомогою функцій numpy.linalg